// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAei5GFRw6wzYCdZZivHGnacP4b2nrycWc',
    appId: '1:775312250904:web:91f7480c4faf0794af8b6d',
    messagingSenderId: '775312250904',
    projectId: 'feedneedy-d4c84',
    authDomain: 'feedneedy-d4c84.firebaseapp.com',
    storageBucket: 'feedneedy-d4c84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxVNOP0jxpckct9TcnMrQVVYrPh8yFwI',
    appId: '1:775312250904:android:97cda21be94a6f05af8b6d',
    messagingSenderId: '775312250904',
    projectId: 'feedneedy-d4c84',
    storageBucket: 'feedneedy-d4c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tjRg6OYo9Fx-iMUz9BLVeCblYzP72DU',
    appId: '1:775312250904:ios:5c12072b31b6f1f3af8b6d',
    messagingSenderId: '775312250904',
    projectId: 'feedneedy-d4c84',
    storageBucket: 'feedneedy-d4c84.firebasestorage.app',
    iosBundleId: 'com.needyfeed.fooddonationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tjRg6OYo9Fx-iMUz9BLVeCblYzP72DU',
    appId: '1:775312250904:ios:39cf03f06e3c4722af8b6d',
    messagingSenderId: '775312250904',
    projectId: 'feedneedy-d4c84',
    storageBucket: 'feedneedy-d4c84.firebasestorage.app',
    iosBundleId: 'com.example.foodadoptionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAei5GFRw6wzYCdZZivHGnacP4b2nrycWc',
    appId: '1:775312250904:web:4264a3edc95a731caf8b6d',
    messagingSenderId: '775312250904',
    projectId: 'feedneedy-d4c84',
    authDomain: 'feedneedy-d4c84.firebaseapp.com',
    storageBucket: 'feedneedy-d4c84.firebasestorage.app',
  );

}