// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83-HfGKDPrrb9D-Z9y9r4cpNrwcfoKHc',
    appId: '1:963314008421:web:29b6d8482ae3147ace218c',
    messagingSenderId: '963314008421',
    projectId: 'fooddenotation',
    authDomain: 'fooddenotation.firebaseapp.com',
    storageBucket: 'fooddenotation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPL63exss_qP5Nocp-vr6s_tHbSvbOFPo',
    appId: '1:963314008421:android:015cff398981958ace218c',
    messagingSenderId: '963314008421',
    projectId: 'fooddenotation',
    storageBucket: 'fooddenotation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZ3k5MlfVO12XyGfveSSDbn8nQAQldJY',
    appId: '1:963314008421:ios:7c0606aa1e080c48ce218c',
    messagingSenderId: '963314008421',
    projectId: 'fooddenotation',
    storageBucket: 'fooddenotation.firebasestorage.app',
    iosBundleId: 'com.needyfeed.fooddonationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxZ3k5MlfVO12XyGfveSSDbn8nQAQldJY',
    appId: '1:963314008421:ios:e5eb96b87b8a81ddce218c',
    messagingSenderId: '963314008421',
    projectId: 'fooddenotation',
    storageBucket: 'fooddenotation.firebasestorage.app',
    iosBundleId: 'com.example.foodadoptionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA83-HfGKDPrrb9D-Z9y9r4cpNrwcfoKHc',
    appId: '1:963314008421:web:09e024b93ee257dace218c',
    messagingSenderId: '963314008421',
    projectId: 'fooddenotation',
    authDomain: 'fooddenotation.firebaseapp.com',
    storageBucket: 'fooddenotation.firebasestorage.app',
  );
}
